[package]
name = "plugin-rust"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
libloe = { git = "https://github.com/lausek/libloe" }
