[package]
name = "loe"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[dependencies]
libloe = { path = "../libloe" }
lazy_static = "1.2.0"
libloading = "0.5"
rustbox = "^0.11.0"

[[bin]]
name = "loe"
path = "src/bin.rs"
